-- Initialize the database.
-- Drop any existing data and create empty tables.

DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Car;
DROP TABLE IF EXISTS Booking;

CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UserName TEXT UNIQUE NOT NULL,
  Password TEXT NOT NULL,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Email TEXT NOT NULL,
  UserType TEXT NOT NULL
);

CREATE TABLE Car (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Make varchar NOT NULL,
  Body TEXT NOT NULL,
  Colour TEXT NOT NULL,
  Seats INTEGER NOT NULL,
  Location TEXT NOT NULL,
  Cost INTEGER NOT NULL,
  Status TEXT NOT NULL DEFAULT "Available",
  AP TEXT
);

CREATE TABLE Booking (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Car TEXT NOT NULL,
  User Text NOT NULL,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  StartTime DATETIME NOT NULL,
  EndTime DATETIME Not Null,
  FOREIGN KEY (Car) REFERENCES Car (id),
  FOREIGN KEY (User) REFERENCES User (id)
);

